services:
  - type: web
    name: calories-protein-calculator
    env: node
    plan: free
    buildCommand: ""
    startCommand: node server.js
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: NUTRITIONIX_APP_ID
        sync: false
      - key: NUTRITIONIX_API_KEY
        sync: false
